### ISSUE TITLE
Prowlarr setup cannot display chosen indexers, error in log 'list' object has no attribute 'id'

### ISSUE THREAD

**Issue by yroyathon** [markbeep/AudioBookRequest#107]
I keep having this intermittent issue where ABR cannot display the indexers that I've selected in its Prowlarr setup.  I've tried restarting the docker container, as well as pruning it and re-pulling the image.  Sometimes that works, but not for long.

from the log file...
INFO   172.26.0.1:35076 - "GET /settings/account HTTP/1.1" 200
2025-05-22 13:07:27,395 [ERROR] app.internal.prowlarr.prowlarr: Failed to access Prowlarr to fetch indexers: 'list' object has no attribute 'id'

Screenshot of ABR UI, shows this instead of the selected indexers
![Image](https://github.com/user-attachments/assets/0e0f5cc6-662d-4ad0-a82c-e1cc3ff3c624)

**Comment by yroyathon** [comment]
I think maybe I made changes to the selected indexers but then forgot to click the Save button in ABR,  then just navigated away to other parts of ABR.  I'll see if having saved it now, whether the issue happens again or not.

**Comment by yroyathon** [comment]
Nope, it happened again.  It also doesn't appear to have saved my selections correctly.  In my indexer list, I removed my usenet indexers since it keeps grabbing the wrong book.  But even having saved it now, it's still querying a usenet indexer that I do not have in my selected indexers in the prowlarr setup.  Weird.

**Comment by markbeep** [comment]
Should have been resolved in 096d04e33d055a5bc0c28b4f4b41c5a783b53b40. If it happens again, I'll reopen the issue.

**Comment by mpalatsi** [comment]
This is still happening on **v1.10.6**, and I think I've found the root cause.

`SimpleCache` in `app/util/cache.py` declares `_cache` as a **class attribute**, so every instance shares one dictionary:

```python
class SimpleCache[VT, *KTs]:
    _cache: dict[tuple[*KTs], tuple[int, VT]] = {}
```

`prowlarr_source_cache` (values are `list[ProwlarrSource]`) and `prowlarr_indexer_cache` (values are `Indexer`) are separate instances, but they write into the same dict. `get_indexers()` then calls `prowlarr_indexer_cache.get_all(...)`, receives the cached *source lists* as well, and `{indexer.id: indexer for indexer in indexers}` raises `AttributeError: 'list' object has no attribute 'id'`.

That also explains the intermittency reported above: the settings page only breaks **after a book search has populated the source cache**. Restarting the container clears it, which is why it appears to fix itself for a while.

Minimal reproduction, no ABR instance required:

```python
from app.util.cache import SimpleCache

a = SimpleCache()
b = SimpleCache()
a.set(["i am a list of sources"], "some-book-title")

print(b.get_all(99999))   # {('some-book-title',): ['i am a list of sources']}
print(a._cache is b._cache)  # True
```

Output on v1.10.6:

```
A.set() stored a LIST under key (some-book-title,)
B.get_all() returns: {('some-book-title',): ['i am a list of sources']}
same underlying dict object: True
→ AttributeError: 'list' object has no attribute 'id'
```

Regarding the commit this was closed against (096d04e3): as far as I can tell it doesn't modify `app/util/cache.py` — that file isn't in the commit's changed-file list, and `_cache` is still a class attribute on `main` today. So the sharing behaviour appears never to have been addressed; the refactor likely just changed the timing of when the collision surfaces.

Fix should be to give each instance its own dict:

```python
class SimpleCache[VT, *KTs]:
    def __init__(self) -> None:
        self._cache: dict[tuple[*KTs], tuple[int, VT]] = {}
```

Happy to open a PR if that would help.

<sub>Environment: v1.10.6, Docker (`markbeep/audiobookrequest:1`), Prowlarr 2.3.0.5236.</sub>
